/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef serialization_CONSTANTS_H
#define serialization_CONSTANTS_H

#include "serialization_types.h"

namespace thrift { namespace adept { namespace serialization {

class serializationConstants {
 public:
  serializationConstants();

};

extern const serializationConstants g_serialization_constants;

}}} // namespace

#endif