/*******************************************************************************
 * Raytheon BBN Technologies Corp., December 2014
 * 
 * THIS CODE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS
 * OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * 
 * Copyright 2014 Raytheon BBN Technologies Corp.  All Rights Reserved.
 ******************************************************************************/
/**
 * 
 */

/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.adept.common;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EntityMentionObject extends org.apache.thrift.TUnion<EntityMentionObject, EntityMentionObject._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EntityMentionObject");
  private static final org.apache.thrift.protocol.TField CHUNK_FIELD_DESC = new org.apache.thrift.protocol.TField("chunk", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField ENTITY_MENTION_FIELD_DESC = new org.apache.thrift.protocol.TField("entityMention", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CHUNK((short)1, "chunk"),
    ENTITY_MENTION((short)2, "entityMention");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CHUNK
          return CHUNK;
        case 2: // ENTITY_MENTION
          return ENTITY_MENTION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CHUNK, new org.apache.thrift.meta_data.FieldMetaData("chunk", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, thrift.adept.common.ChunkUnion.class)));
    tmpMap.put(_Fields.ENTITY_MENTION, new org.apache.thrift.meta_data.FieldMetaData("entityMention", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EntityMention.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EntityMentionObject.class, metaDataMap);
  }

  public EntityMentionObject() {
    super();
  }

  public EntityMentionObject(_Fields setField, Object value) {
    super(setField, value);
  }

  public EntityMentionObject(EntityMentionObject other) {
    super(other);
  }
  public EntityMentionObject deepCopy() {
    return new EntityMentionObject(this);
  }

  public static EntityMentionObject chunk(thrift.adept.common.ChunkUnion value) {
    EntityMentionObject x = new EntityMentionObject();
    x.setChunk(value);
    return x;
  }

  public static EntityMentionObject entityMention(EntityMention value) {
    EntityMentionObject x = new EntityMentionObject();
    x.setEntityMention(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case CHUNK:
        if (value instanceof thrift.adept.common.ChunkUnion) {
          break;
        }
        throw new ClassCastException("Was expecting value of type thrift.adept.common.ChunkUnion for field 'chunk', but got " + value.getClass().getSimpleName());
      case ENTITY_MENTION:
        if (value instanceof EntityMention) {
          break;
        }
        throw new ClassCastException("Was expecting value of type EntityMention for field 'entityMention', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case CHUNK:
          if (field.type == CHUNK_FIELD_DESC.type) {
            thrift.adept.common.ChunkUnion chunk;
            chunk = new thrift.adept.common.ChunkUnion();
            chunk.read(iprot);
            return chunk;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case ENTITY_MENTION:
          if (field.type == ENTITY_MENTION_FIELD_DESC.type) {
            EntityMention entityMention;
            entityMention = new EntityMention();
            entityMention.read(iprot);
            return entityMention;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CHUNK:
        thrift.adept.common.ChunkUnion chunk = (thrift.adept.common.ChunkUnion)value_;
        chunk.write(oprot);
        return;
      case ENTITY_MENTION:
        EntityMention entityMention = (EntityMention)value_;
        entityMention.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case CHUNK:
          thrift.adept.common.ChunkUnion chunk;
          chunk = new thrift.adept.common.ChunkUnion();
          chunk.read(iprot);
          return chunk;
        case ENTITY_MENTION:
          EntityMention entityMention;
          entityMention = new EntityMention();
          entityMention.read(iprot);
          return entityMention;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CHUNK:
        thrift.adept.common.ChunkUnion chunk = (thrift.adept.common.ChunkUnion)value_;
        chunk.write(oprot);
        return;
      case ENTITY_MENTION:
        EntityMention entityMention = (EntityMention)value_;
        entityMention.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case CHUNK:
        return CHUNK_FIELD_DESC;
      case ENTITY_MENTION:
        return ENTITY_MENTION_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public thrift.adept.common.ChunkUnion getChunk() {
    if (getSetField() == _Fields.CHUNK) {
      return (thrift.adept.common.ChunkUnion)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'chunk' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setChunk(thrift.adept.common.ChunkUnion value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.CHUNK;
    value_ = value;
  }

  public EntityMention getEntityMention() {
    if (getSetField() == _Fields.ENTITY_MENTION) {
      return (EntityMention)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'entityMention' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setEntityMention(EntityMention value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.ENTITY_MENTION;
    value_ = value;
  }

  public boolean isSetChunk() {
    return setField_ == _Fields.CHUNK;
  }


  public boolean isSetEntityMention() {
    return setField_ == _Fields.ENTITY_MENTION;
  }


  public boolean equals(Object other) {
    if (other instanceof EntityMentionObject) {
      return equals((EntityMentionObject)other);
    } else {
      return false;
    }
  }

  public boolean equals(EntityMentionObject other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(EntityMentionObject other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  /**
   * If you'd like this to perform more respectably, use the hashcode generator option.
   */
  @Override
  public int hashCode() {
    return 0;
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
