/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.adept.common;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * The Class Event Relations.
 */
public class EventRelations implements org.apache.thrift.TBase<EventRelations, EventRelations._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EventRelations");

  private static final org.apache.thrift.protocol.TField COREFERENCES_FIELD_DESC = new org.apache.thrift.protocol.TField("coreferences", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EventRelationsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EventRelationsTupleSchemeFactory());
  }

  /**
   * The coreferences
   */
  public List<Event> coreferences; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * The coreferences
     */
    COREFERENCES((short)1, "coreferences");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // COREFERENCES
          return COREFERENCES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.COREFERENCES};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COREFERENCES, new org.apache.thrift.meta_data.FieldMetaData("coreferences", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Event.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EventRelations.class, metaDataMap);
  }

  public EventRelations() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EventRelations(EventRelations other) {
    if (other.isSetCoreferences()) {
      List<Event> __this__coreferences = new ArrayList<Event>();
      for (Event other_element : other.coreferences) {
        __this__coreferences.add(new Event(other_element));
      }
      this.coreferences = __this__coreferences;
    }
  }

  public EventRelations deepCopy() {
    return new EventRelations(this);
  }

  @Override
  public void clear() {
    this.coreferences = null;
  }

  public int getCoreferencesSize() {
    return (this.coreferences == null) ? 0 : this.coreferences.size();
  }

  public java.util.Iterator<Event> getCoreferencesIterator() {
    return (this.coreferences == null) ? null : this.coreferences.iterator();
  }

  public void addToCoreferences(Event elem) {
    if (this.coreferences == null) {
      this.coreferences = new ArrayList<Event>();
    }
    this.coreferences.add(elem);
  }

  /**
   * The coreferences
   */
  public List<Event> getCoreferences() {
    return this.coreferences;
  }

  /**
   * The coreferences
   */
  public EventRelations setCoreferences(List<Event> coreferences) {
    this.coreferences = coreferences;
    return this;
  }

  public void unsetCoreferences() {
    this.coreferences = null;
  }

  /** Returns true if field coreferences is set (has been assigned a value) and false otherwise */
  public boolean isSetCoreferences() {
    return this.coreferences != null;
  }

  public void setCoreferencesIsSet(boolean value) {
    if (!value) {
      this.coreferences = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case COREFERENCES:
      if (value == null) {
        unsetCoreferences();
      } else {
        setCoreferences((List<Event>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case COREFERENCES:
      return getCoreferences();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case COREFERENCES:
      return isSetCoreferences();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EventRelations)
      return this.equals((EventRelations)that);
    return false;
  }

  public boolean equals(EventRelations that) {
    if (that == null)
      return false;

    boolean this_present_coreferences = true && this.isSetCoreferences();
    boolean that_present_coreferences = true && that.isSetCoreferences();
    if (this_present_coreferences || that_present_coreferences) {
      if (!(this_present_coreferences && that_present_coreferences))
        return false;
      if (!this.coreferences.equals(that.coreferences))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(EventRelations other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    EventRelations typedOther = (EventRelations)other;

    lastComparison = Boolean.valueOf(isSetCoreferences()).compareTo(typedOther.isSetCoreferences());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCoreferences()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.coreferences, typedOther.coreferences);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("EventRelations(");
    boolean first = true;

    if (isSetCoreferences()) {
      sb.append("coreferences:");
      if (this.coreferences == null) {
        sb.append("null");
      } else {
        sb.append(this.coreferences);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EventRelationsStandardSchemeFactory implements SchemeFactory {
    public EventRelationsStandardScheme getScheme() {
      return new EventRelationsStandardScheme();
    }
  }

  private static class EventRelationsStandardScheme extends StandardScheme<EventRelations> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, EventRelations struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // COREFERENCES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list236 = iprot.readListBegin();
                struct.coreferences = new ArrayList<Event>(_list236.size);
                for (int _i237 = 0; _i237 < _list236.size; ++_i237)
                {
                  Event _elem238; // required
                  _elem238 = new Event();
                  _elem238.read(iprot);
                  struct.coreferences.add(_elem238);
                }
                iprot.readListEnd();
              }
              struct.setCoreferencesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, EventRelations struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.coreferences != null) {
        if (struct.isSetCoreferences()) {
          oprot.writeFieldBegin(COREFERENCES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.coreferences.size()));
            for (Event _iter239 : struct.coreferences)
            {
              _iter239.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EventRelationsTupleSchemeFactory implements SchemeFactory {
    public EventRelationsTupleScheme getScheme() {
      return new EventRelationsTupleScheme();
    }
  }

  private static class EventRelationsTupleScheme extends TupleScheme<EventRelations> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EventRelations struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCoreferences()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetCoreferences()) {
        {
          oprot.writeI32(struct.coreferences.size());
          for (Event _iter240 : struct.coreferences)
          {
            _iter240.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EventRelations struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list241 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.coreferences = new ArrayList<Event>(_list241.size);
          for (int _i242 = 0; _i242 < _list241.size; ++_i242)
          {
            Event _elem243; // required
            _elem243 = new Event();
            _elem243.read(iprot);
            struct.coreferences.add(_elem243);
          }
        }
        struct.setCoreferencesIsSet(true);
      }
    }
  }

}