/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.adept.common;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TranslatorType implements org.apache.thrift.TEnum {
  NONE(0),
  SDL_LW(1);

  private final int value;

  private TranslatorType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TranslatorType findByValue(int value) { 
    switch (value) {
      case 0:
        return NONE;
      case 1:
        return SDL_LW;
      default:
        return null;
    }
  }
}
